### ISSUE TITLE
Opening jobs into a new tab fails

### ISSUE THREAD

**Issue by jguitar** [VLCTechHub/VLCTechHub#41]
Opening links from https://vlctechhub.org/job/board into a separate window or tab fails because it generates bad URLs (e.g. https://vlctechhub.org/job/job/board/3b3be332-fd33-45ae-a6cb-c75c4ba895fe) duplicating the slug _job_.

@hell03610 suggests to use [`link-to`](https://guides.emberjs.com/v2.7.0/templates/links/) instead of `a` tag at https://github.com/VLCTechHub/VLCTechHub/blob/master/app/pods/components/job/job-row/template.hbs#L11

**Comment by jguitar** [comment]
I made those changes:
```diff
-            <a href='job/board/{{item.id}}' class='title' title="{{item.title}}">
+            {{#link-to 'job.list.detail' item class='title' title=item.title}}
               {{shorten-text item.title 55}}
-            </a>
+            {{/link-to}}
```
But tests are failing. I'm trying to fix them.

**Comment by hell03610** [comment]
Thx, I had a look a it. With fixed link, it makes no sense to do the collapse/expand job detail when clicking on the name, as the name is a link to navigate to details (which is what tests were checking). I'll remove the actions and the tests.
