### ISSUE TITLE
Blank screen on Nexus 5 devices

### ISSUE THREAD

**Issue by DavidHernandez** [VLCTechHub/VLCTechHub#46]
This could be a duplication of #37

**Comment by DavidHernandez** [comment]
From the slack conversation:
<img width="1036" alt="error" src="https://cloud.githubusercontent.com/assets/877002/26155894/fa807d56-3b14-11e7-95d9-7cd45f97fa7b.png">

**Comment by DavidHernandez** [comment]
The above image seems to confirm that this is indeed a duplication of #37

**Comment by DavidHernandez** [comment]
This issue has been confirmed on at least 3 different Nexus 5. There is one reported Nexus 5 where the issue is not happening. Trying to get the chrome versions.

The browsers that seem to be failing so far are Chrome and the reported versions are 58.0.3029 and 57.0.2987.132.

The browser where seems to be working is also Chrome, running version 58.0.3029.83

**Comment by DavidHernandez** [comment]
![captura de pantalla 2017-05-17 a las 15 28 14](https://cloud.githubusercontent.com/assets/877002/26156207/df3ad73e-3b15-11e7-9597-9a035f438b71.png)

**Comment by DavidHernandez** [comment]
This might be related: https://github.com/ember-cli/ember-cli/issues/5040

**Comment by DavidHernandez** [comment]
When viewing the HTML source of the page (in the repo does not appear), we find two cases of the integrity attribute being used:

```
    <script src="/assets/vendor-35aea396574469edfba68e595608c708.js" integrity="sha256-Z8Q3cTAE9fMvOdI+mFuWQlnf+DKfHqGo/tTwuO0dxCA= sha512-4i7Vtkvgykgag59sLoIzYyqzi7xfl9hGCzirotVtg6VuyYbV1BCF1QHKRkzHHA8eWYwIS2kmXihlUmrJ0yjY4Q==" ></script>
    <script src="/assets/vlc-tech-hub-62c894c7b9bd0eec8f0f81fbfd5fc5f2.js" integrity="sha256-2x0+kxCOHDegTJft9k8MpdyoWw94OEGS4jdg//ny4t0= sha512-Y76iUhjP3I7NE3rxpOpXrxTqHk4E366188PVrhEY9y/xQSRNW7ksPwXYaJp7lK2aGujC5DA1SOGnGSEAzlngqA==" ></script>
```

**Comment by hell03610** [comment]
It's an issue with some versions of Chrome and some settings apparently
https://github.com/facebookincubator/create-react-app/issues/1231#issuecomment-266233702

It seems we could force to serve vlctechhub.org through https

**Comment by hell03610** [comment]
Solved serving website in https
