### ISSUE TITLE
VLCTechFest 2018 announcement is still visible

### ISSUE THREAD

**Issue by esebastian** [VLCTechHub/VLCTechHub#48]
In spite of https://github.com/VLCTechHub/VLCTechHub/blob/master/app/pods/event/upcoming/controller.js#L11 and https://github.com/VLCTechHub/VLCTechHub/blob/master/app/pods/event/upcoming/template.hbs#L23

**Comment by jguitar** [comment]
I don't see the announcement! 
![image](https://user-images.githubusercontent.com/761794/41522831-06c4ea38-72d8-11e8-880b-5872f9c2160b.png)

Could be some cache issue?

**Comment by esebastian** [comment]
The issue is happening in the [VLCTechHub](vlctechhub.org) site, not in the [VLCTechFest](vlctechfest.org) one:

![screen shot 2018-06-18 at 11 57 48](https://user-images.githubusercontent.com/577074/41530009-16f91a0c-72ef-11e8-8884-db82868ddce9.png)

**Comment by jguitar** [comment]
Oops, sorry. My fault 😅

**Comment by jguitar** [comment]
I found the error and made a PR to fix this, take a look @esebastian
